### ISSUE TITLE
Enhancements for the Rules API

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#636]
With the latest refactoring of Activator into Controller, much of the groundwork has been done to implement some enhancements for the Rules API.
- [x] Ability to add actions to a rule that are not in the same namespace as the rule itself (including actions in packages, #239)
- [x] Make rules enabled by default
- [ ] List all rules (actions) associated with a trigger (#324)
- [ ] Allow for anonymous rules (#833)

**Comment by starpit** [comment]
i'm working on rules enabled by default

**Comment by markusthoemmes** [comment]
Covered in more precise issues.
